'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class PROMOTION_prom_rev_report_f6cc97c59897
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
End Class
