'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pl3_Dep_Head_Updation_97e1dc308577

    '''<summary>
    '''cmb_Major control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_Major As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmb_Sub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_Sub As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_DepHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DepHead As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_NewHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NewHead As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As WebAppHRMS.edp
        Get
            Return CType(MyBase.Master, WebAppHRMS.edp)
        End Get
    End Property
End Class
