Imports System.Data
Imports System.Data.OracleClient
Imports CrystalDecisions.Shared
Imports CrystalDecisions.CrystalReports.Engine
Partial Class payroll_pl3_rep_d5eaa1d83074
    Inherits System.Web.UI.Page
    Dim report As New ReportDocument
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Dim oh As New Helper.Oracle.OracleHelper
        Dim dt, dt1, dt2 As New DataTable
        Dim sql, sql1 As String
        'sql = "select c.branch_name,d.name||' '||b.br_name||',A/C NO:'||a.bank_accno as bank,a.actual_bal,e.reason,a.req_amt,a.explanation from fundtfr_dtl a,bank_accno b,branch_master c,bank d,ftfr_reason e where a.branch_id=c.branch_id and a.branch_id=b.branch_id and a.bank_accno=b.bankacc_no and a.bank_id=d.bank_id and b.bank_id=d.bank_id and a.approved='T' and a.confirm_reso='T' and a.reason=e.r_id"
        'sql = "select c.branch_name,b.emp_name||' '||a.emp_code  employee,d.post_name,e.dep_name,'TOUR' particulars,'TOUR TO '||f.branch_name reason,a.emp_code from attend a,employee_master b,branch_master c,post_mst d,department_mst e,branch_master f where a.emp_code=b.emp_code and a.m_branch<>a.branch_id and m_time is not NULL and a.branch_id=c.branch_id and b.post_id=d.post_id and b.department_id=e.dep_id and a.m_branch=f.branch_id and to_date(a.curr_date)= '" & Request.QueryString.Get("dt") & "' union all select c.branch_name,b.emp_name||' '||a.emp_code as Employee,d.post_name,e.dep_name,case when a.leave_type=0 then 'NOT INFORMED' when a.leave_type=1 then 'INFORMED' when a.leave_type=2 then 'APPROVED' when a.leave_type=5 then 'COMPENSATORY OFF' when a.leave_type=7 then 'TOUR' end as particulars,a.reason,a.emp_code from leave_pl3 a,employee_master b,branch_master c,post_mst d,department_mst e where a.emp_code=b.emp_code and a.branch_id=c.branch_id and d.post_id=b.post_id and e.dep_id=b.department_id and to_date(leave_date)='" & Request.QueryString.Get("dt") & "' union all select c.branch_name,d.emp_name||' '||a.emp_code as employee,f.post_name,e.dep_name,b.leave_type as particulars,a.leave_reason as reason,a.emp_code from employ_leave_dtl a,leave_master b,branch_master c,employee_master d,department_mst e,post_mst f where a.emp_code=d.emp_code and d.branch_id=c.branch_id and d.department_id=e.dep_id and d.post_id=f.post_id and a.leave_id=b.leave_id and '" & Request.QueryString.Get("dt") & "' between to_date(leave_frdate) and to_date(leave_todate) order by branch_name"
        If Request.QueryString.Get("dt") = Format(Date.Today, "dd/MMM/yyyy") Then
            sql = "select upper(c.branch_name) branch_name,  upper(substr(b.emp_name, 0, 20)) employee,  upper(substr(d.post_name, 0, 15)) post_name,  upper(substr(e.dep_name, 0, 18)) dep_name,  case  when a.leave_type = 0 then  'NOT INFORMED'  when a.leave_type = 1 then  'INFORMED'  when a.leave_type = 2 then  'APPROVED'  when a.leave_type = 5 then  'COMPENSATORY OFF'  when a.leave_type = 7 then  'TOUR'  when a.leave_type = 3 then  'SHIFT'  end as particulars,  a.reason,  a.emp_code,  b.branch_id  from leave_pl3       a,  employee_master b,  branch_master   c,  post_mst        d,  department_mst  e,  employ_firm     ef  where a.emp_code = b.emp_code  and a.branch_id = c.branch_id  and d.post_id = b.post_id  and e.dep_id = b.department_id  and b.emp_code = ef.emp_code  and ef.firm_id = '" & Session("firm_id") & "'  and to_date(leave_date) = '" & Request.QueryString.Get("dt") & "' union select c.branch_name,  d.emp_name || ' ' || a.emp_code as employee,  f.post_name,  e.dep_name,  b.leave_type as particulars,  a.leave_reason as reason,  a.emp_code,  c.branch_id  from employ_leave_dtl a,  leave_master     b,  branch_master    c,  employee_master  d,  department_mst   e,  post_mst         f,  employ_firm      ef  where a.emp_code = d.emp_code  and d.branch_id = c.branch_id  and d.department_id = e.dep_id  and d.post_id = f.post_id  and a.leave_id = b.leave_id  and d.emp_code = ef.emp_code  and ef.firm_id = '" & Session("firm_id") & "'  and '" & Request.QueryString.Get("dt") & "' between  to_date(leave_frdate) and to_date(leave_todate)  and not exists  (select emp_code  from leave_pl3 b  where a.emp_code = b.emp_code  and to_date(b.leave_date) =  '" & Request.QueryString.Get("dt") & "') union select upper(c.branch_name) branch_name,  upper(substr(b.emp_name, 0, 20)) employee,  upper(substr(d.post_name, 0, 15)) post_name,  upper(substr(e.dep_name, 0, 18)) dep_name,  NULL particulars,  NULL reason,  a.emp_code,  a.branch_id  from daily_attend    a,  employee_master b,  branch_master   c,  post_mst        d,  department_mst  e,  employ_firm     ef  where m_time is NULL  and a.shift_id not in (4, 5)  and a.emp_code = b.emp_code  and a.branch_id = c.branch_id  and d.post_id = b.post_id  and e.dep_id = b.department_id  and b.emp_code = ef.emp_code  and ef.firm_id = '" & Session("firm_id") & "'  and to_date(curr_date) = '" & Request.QueryString.Get("dt") & "'  and not exists  (select emp_code  from leave_pl3 b  where a.emp_code = b.emp_code  and to_date(b.leave_date) =  '" & Request.QueryString.Get("dt") & "')  order by branch_id, dep_name"
            sql1 = "select a.branch_id, count(*) as total  from daily_attend a,employ_firm ef  where m_time is Null  and shift_id not in (4, 5)  and a.emp_code=ef.emp_code  and ef.firm_id='" & Session("firm_id") & "'  group by a.branch_id  order by a.branch_id"
        Else
            sql = "select upper(c.branch_name) branch_name,  upper(substr(b.emp_name, 0, 20)) employee,  upper(substr(d.post_name, 0, 15)) post_name,  upper(substr(e.dep_name, 0, 18)) dep_name,  case  when a.leave_type = 0 then  'NOT INFORMED'  when a.leave_type = 1 then  'INFORMED'  when a.leave_type = 2 then  'APPROVED'  when a.leave_type = 5 then  'COMPENSATORY OFF'  when a.leave_type = 7 then  'TOUR'  when a.leave_type = 3 then  'SHIFT'  end as particulars,  a.reason,  a.emp_code,  b.branch_id  from leave_pl3       a,  employee_master b,  branch_master   c,  post_mst        d,  department_mst  e,  employ_firm     ef  where a.emp_code = b.emp_code  and a.branch_id = c.branch_id  and d.post_id = b.post_id  and e.dep_id = b.department_id  and b.emp_code = ef.emp_code  and ef.firm_id = '" & Session("firm_id") & "'  and to_date(leave_date) = '" & Request.QueryString.Get("dt") & "' union select c.branch_name,  d.emp_name || ' ' || a.emp_code as employee,  f.post_name,  e.dep_name,  b.leave_type as particulars,  a.leave_reason as reason,  a.emp_code,  c.branch_id  from employ_leave_dtl a,  leave_master     b,  branch_master    c,  employee_master  d,  department_mst   e,  post_mst         f,  employ_firm      ef  where a.emp_code = d.emp_code  and d.branch_id = c.branch_id  and d.department_id = e.dep_id  and d.post_id = f.post_id  and d.emp_code=ef.emp_code  and ef.firm_id='" & Session("firm_id") & "'  and a.leave_id = b.leave_id  and '" & Request.QueryString.Get("dt") & "' between  to_date(leave_frdate) and to_date(leave_todate)  and not exists  (select emp_code  from leave_pl3 b  where a.emp_code = b.emp_code  and to_date(b.leave_date) =  '" & Request.QueryString.Get("dt") & "') union select upper(c.branch_name) branch_name,  upper(substr(b.emp_name, 0, 20)) employee,  upper(substr(d.post_name, 0, 15)) post_name,  upper(substr(e.dep_name, 0, 18)) dep_name,  NULL particulars,  NULL reason,  a.emp_code,  a.branch_id  from daily_attend    a,  employee_master b,  branch_master   c,  post_mst        d,  department_mst  e,  employ_firm     ef  where m_time is NULL  and a.shift_id not in (4, 5)  and a.emp_code = b.emp_code  and a.branch_id = c.branch_id  and d.post_id = b.post_id  and e.dep_id = b.department_id  and b.emp_code = ef.emp_code  and ef.firm_id='" & Session("firm_id") & "'  and to_date(curr_date) = '" & Request.QueryString.Get("dt") & "'  and not exists  (select emp_code  from leave_pl3 b  where a.emp_code = b.emp_code  and to_date(b.leave_date) =  '" & Request.QueryString.Get("dt") & "')  order by branch_id, dep_name"
            sql1 = "select a.branch_id,count(*) as total  from attend a where  m_time is Null and shift_id not in (4,5) and to_date(curr_date)='" & Request.QueryString.Get("dt") & "' group by a.branch_id order by a.branch_id"
        End If
        dt = oh.ExecuteDataSet(sql).Tables(0)
        dt1 = oh.ExecuteDataSet("select a.branch_id, count(*) as total  from employee_master a,employ_firm ef  where a.status_id = 1  and shift_id not in (4, 5)  and a.emp_code=ef.emp_code  and ef.firm_id='" & Session("firm_id") & "'  group by a.branch_id  order by a.branch_id").Tables(0)
        dt2 = oh.ExecuteDataSet(sql1).Tables(0)
        report.Load(Server.MapPath("pl3rep.rpt"), OpenReportMethod.OpenReportByTempCopy)
        report.Database.Tables("pl3").SetDataSource(dt)
        report.Database.Tables("strength").SetDataSource(dt1)
        report.Database.Tables("punched").SetDataSource(dt2)
        report.SetParameterValue("dt", Request.Querystring.Get("dt"))
        report.SetParameterValue("FIRM", Session("firm_name"))
        Me.CrystalReportViewer1.ReportSource = report
    End Sub
    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload
        report.Close()
        report.Dispose()
        GC.Collect()
    End Sub
End Class
