'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AnyTimePunching_New_hrm_Punch_Regular_Form_96f032a99538

    '''<summary>
    '''rdb_All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdb_All As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdb_Indi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdb_Indi As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdb_Nonmarking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdb_Nonmarking As Global.System.Web.UI.WebControls.RadioButton
End Class
