'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Sunday_lopCancellationRequest_78fdc6344226

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chk_rec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_rec As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_app As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddl_lop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_lop As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_empcd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_empcd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_empnme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_empnme As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_branch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_branch As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_post control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_post As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtworked_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtworked_date As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtlopcanclltn_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlopcanclltn_date As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtemp_rmrks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtemp_rmrks As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtapplied_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtapplied_date As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_remarks As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''emp_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emp_type As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Hidden1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hidden1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hid_user control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hid_user As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hid_rej control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hid_rej As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hid_access control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hid_access As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''cmd_rec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_rec As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmd_app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_app As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmd_rej control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_rej As Global.System.Web.UI.WebControls.Button
End Class
