Imports System.Data
Imports System.Data.OracleClient

Partial Class employee_report_emprep_bb4a3f117745
    Inherits System.Web.UI.Page
    Dim oh As New Helper.Oracle.OracleHelper
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Dim cs As String = "var cont_name;cont_name='" & Me.Chk_age.ClientID & "';"
        Page.ClientScript.RegisterClientScriptBlock(Me.GetType, "var", cs, True)

        If Not IsPostBack Then
            'post
            Dim dt As DataTable = oh.ExecuteDataSet("select post_id,post_name from post_mst order by post_name").Tables(0)
            Me.cmb_post.DataSource = dt
            Me.cmb_post.DataTextField = dt.Columns(1).ColumnName
            Me.cmb_post.DataValueField = dt.Columns(0).ColumnName
            Me.cmb_post.DataBind()

            'qualification
            Dim dt1 As DataTable = oh.ExecuteDataSet("select qualification_id,qualification from qualification_master order by qualification").Tables(0)
            Me.cmb_qualif.DataSource = dt1
            Me.cmb_qualif.DataTextField = dt1.Columns(1).ColumnName
            Me.cmb_qualif.DataValueField = dt1.Columns(0).ColumnName
            Me.cmb_qualif.DataBind()
            Me.txt_from.Text = Format(Now.Date, "dd/MMM/yyyy")
            Me.txt_to.Text = Format(Now.Date, "dd/MMM/yyyy")
            Me.cmb_post.Enabled = False
            Me.cmb_qualif.Enabled = False
            Me.cmb_gender.Enabled = False
            Me.txt_agefrom.Enabled = False
            Me.txt_ageto.Enabled = False
        End If

    End Sub

    Protected Sub cmd_confirm_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles cmd_confirm.Click
        Dim sql As String = ""

        '4 checked
        If Me.chk_qualif.Checked = True And Me.Chk_post.Checked = True And Me.chk_gender.Checked = True And Me.Chk_age.Checked = True Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br,employ_firm ef where e.emp_code=ep.emp_code and e.emp_code = ef.emp_code  and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            '3 checked
        ElseIf Me.chk_qualif.Checked = True And Me.Chk_post.Checked = True And Me.chk_gender.Checked = True And Me.Chk_age.Checked = False Then
            '  sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "')order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code  and e.emp_code = ef.emp_code and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "')order by e.emp_code"

        ElseIf Me.chk_qualif.Checked = True And Me.Chk_post.Checked = True And Me.chk_gender.Checked = False And Me.Chk_age.Checked = True Then
            ' sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br,employ_firm ef where e.emp_code=ep.emp_code and e.emp_code = ef.emp_code and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
        ElseIf Me.chk_qualif.Checked = True And Me.Chk_post.Checked = False And Me.chk_gender.Checked = True And Me.Chk_age.Checked = True Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and ep.sex=" & Me.cmb_gender.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.emp_code = ef.emp_code  and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and ep.sex=" & Me.cmb_gender.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
        ElseIf Me.chk_qualif.Checked = False And Me.Chk_post.Checked = True And Me.chk_gender.Checked = True And Me.Chk_age.Checked = True Then
            ' sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e, employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code  and e.emp_code = ef.emp_code and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"

            '2 checked
        ElseIf Me.chk_qualif.Checked = True And Me.Chk_post.Checked = True And Me.chk_gender.Checked = False And Me.Chk_age.Checked = False Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code  and e.emp_code = ef.emp_code and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
        ElseIf Me.chk_qualif.Checked = True And Me.Chk_post.Checked = False And Me.chk_gender.Checked = True And Me.Chk_age.Checked = False Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code  and e.emp_code = ef.emp_code  and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
        ElseIf Me.chk_qualif.Checked = False And Me.Chk_post.Checked = True And Me.chk_gender.Checked = True And Me.Chk_age.Checked = False Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code  and e.emp_code = ef.emp_code and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.post_id=" & Me.cmb_post.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
        ElseIf Me.chk_qualif.Checked = True And Me.Chk_post.Checked = False And Me.chk_gender.Checked = False And Me.Chk_age.Checked = True Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code  and e.emp_code = ef.emp_code  and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
        ElseIf Me.chk_qualif.Checked = False And Me.Chk_post.Checked = False And Me.chk_gender.Checked = True And Me.Chk_age.Checked = True Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and ep.sex=" & Me.cmb_gender.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e, employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code  and e.emp_code = ef.emp_code  and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and ep.sex=" & Me.cmb_gender.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
        ElseIf Me.chk_qualif.Checked = False And Me.Chk_post.Checked = True And Me.chk_gender.Checked = False And Me.Chk_age.Checked = True Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and e.post_id=" & Me.cmb_post.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.emp_code = ef.emp_code and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and e.post_id=" & Me.cmb_post.SelectedValue & " and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"

            '1 checked
        ElseIf Me.chk_qualif.Checked = True And Me.Chk_post.Checked = False And Me.chk_gender.Checked = False And Me.Chk_age.Checked = False Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.emp_code = ef.emp_code and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and eq.qualification=" & Me.cmb_qualif.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
        ElseIf Me.chk_qualif.Checked = False And Me.Chk_post.Checked = True And Me.chk_gender.Checked = False And Me.Chk_age.Checked = False Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and e.post_id=" & Me.cmb_post.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e, employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.emp_code = ef.emp_code  and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and e.post_id=" & Me.cmb_post.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
        ElseIf Me.chk_qualif.Checked = False And Me.Chk_post.Checked = False And Me.chk_gender.Checked = True And Me.Chk_age.Checked = False Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code  and e.emp_code = ef.emp_code  and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and ep.sex=" & Me.cmb_gender.SelectedValue & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
        ElseIf Me.chk_qualif.Checked = False And Me.Chk_post.Checked = False And Me.chk_gender.Checked = False And Me.Chk_age.Checked = True Then
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code  and e.emp_code = ef.emp_code  and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and (to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) between " & Me.txt_agefrom.Text & " and " & Me.txt_ageto.Text & " and e.join_dt between to_date('" & Me.txt_from.Text & "') and to_date('" & Me.txt_to.Text & "') and e.status_id=1 order by e.emp_code"

            'to view all
        Else
            'sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and e.status_id=1  order by e.emp_code"
            sql = "select e.emp_code || ' - ' ||upper(e.emp_name),upper(br.branch_name),upper(qm.qualification),upper(p.post_name),ep.sex,to_number(to_char(sysdate,'YYYY'))-to_number(to_char(to_date(ep.birth_date),'YYYY')) age,e.join_dt from employee_master e,  employ_firm ef,employ_personal_dtl ep,post_mst p,employ_qualification_dtl eq,qualification_master qm,branch_master br where e.emp_code=ep.emp_code  and e.emp_code = ef.emp_code and ef.firm_id = " & Session("firm_id") & " and e.post_id=p.post_id and e.emp_code=eq.emp_code and eq.qualification=qm.qualification_id and e.branch_id=br.branch_id and (eq.emp_code,eq.year_pass) in (select distinct emp_code,max(year_pass) from employ_qualification_dtl group by emp_code) and e.status_id=1  order by e.emp_code"
        End If
        Me.Server.Transfer("rep_emprep.aspx?sql=" & sql)

    End Sub


    Protected Sub chk_qualif_CheckedChanged(ByVal sender As Object, ByVal e As System.EventArgs)
        If Me.chk_qualif.Checked = True Then
            Me.cmb_qualif.Enabled = True
        Else
            Me.cmb_qualif.Enabled = False
        End If
    End Sub

    Protected Sub Chk_post_CheckedChanged(ByVal sender As Object, ByVal e As System.EventArgs)
        If Me.Chk_post.Checked = True Then
            Me.cmb_post.Enabled = True
        Else
            Me.cmb_post.Enabled = False
        End If
    End Sub

    Protected Sub chk_gender_CheckedChanged(ByVal sender As Object, ByVal e As System.EventArgs)
        If Me.chk_gender.Checked = True Then
            Me.cmb_gender.Enabled = True
        Else
            Me.cmb_gender.Enabled = False
        End If
    End Sub

    Protected Sub Chk_age_CheckedChanged(ByVal sender As Object, ByVal e As System.EventArgs)
        If Me.Chk_age.Checked = True Then
            Me.txt_agefrom.Enabled = True
            Me.txt_ageto.Enabled = True
        Else
            Me.txt_agefrom.Enabled = False
            Me.txt_ageto.Enabled = False
        End If
    End Sub
End Class
