'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class payroll_posting_appl_other_detail_3df3eea01904

    '''<summary>
    '''txt_appno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_appno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_appname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_appname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_emp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_emp As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txt_empname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_empname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_emprelation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_emprelation As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_director control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_director As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txt_directorname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_directorname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_directorrelation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_directorrelation As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_ref1name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ref1name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_ref2name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ref2name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_ref1address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ref1address As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_ref2address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ref2address As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_ref1phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ref1phone As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_ref2phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ref2phone As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_other As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cmd_add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_add As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As WebAppHRMS.edp
        Get
            Return CType(MyBase.Master, WebAppHRMS.edp)
        End Get
    End Property
End Class
