Imports system.data
Imports System.Data.OracleClient
Imports CrystalDecisions.Shared
Imports CrystalDecisions.CrystalReports.Engine
Partial Class newresign_resign_view__report2_d77ee9582303
    Inherits System.Web.UI.Page
    Dim oh As New helper.oracle.OracleHelper
    Dim dt As New DataTable
    Dim fdt, tdt, emp, sql, sql1, usr As String
    Dim report As New ReportDocument
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        fdt = Request.QueryString.Get("fdt")
        tdt = Request.QueryString.Get("tdt")
        usr = Request.QueryString.Get("usr")
        Dim fir = Session("firm_id")
        Dim dt, dt1, dt2 As New DataTable
        dt1 = oh.ExecuteDataSet("select e.access_id from employee_master e where e.emp_code =  '" & usr & "'").Tables(0)
        dt2 = oh.ExecuteDataSet("select e.emp_code  from employee_master e where e.department_id=290 and e.post_id=85 and e.emp_code =  '" & usr & "'").Tables(0)
        If dt1.Rows(0)(0) = 33 Then
            dt = oh.ExecuteDataSet("select e.emp_code,m.emp_name,b.BRANCH_NAME,ec.gender,b.area_name,b.reg_name,b.ZONAL_NAME,st.state_name,ec.designation, ec.exp_day, ec.qualification,to_date(e.enter_dt) as Apply_dt, to_date(e.resign_dt) as Resign_dt, to_date(e.relieve_dt) as Relieve_dt, case  when e.reason = 1 then  hs.college_nm || ' , ' || hs.course || ' , ' || hs.durtion  else   case        when e.reason = 2 then          pr.reason         else          case         when e.reason = 3 then          oe.firm || ' , ' || oe.reason || ' , ' || oe.nature_work || ' , ' ||          oe.salary         else          case         when e.reason = 4 then          mr.partner_name || ' , ' || mr.job_partner || ' , ' ||    mr.place_marriage  else   case  when e.reason = 5 then  rr.reason       end end end end end as reason,       case         when e.status = 0 then          'Applied' else case  when e.status = 1 then 'Approved' else  case  when e.status = 2 then 'Resigned' else  case when e.status = 3 then  'Cancelled'  else   case  when e.status = 5 then 'Processed'  end end end end end as status,e.approved_by || '--' || e1.emp_name as approved_by,to_date(e.approve_dt) as approve_dt,e.cancel_by || '--' || e2.emp_name as cancel_by,to_date(e.cancel_dt) as Cancel_dt  from employee_master  m,employ_firm f ,employee_current ec,       branch_dtl_new   b,        post_master      ps,       district_master  ds,       state_master     st,       employ_personal_dtl ep,       m_resign_appl    e  left outer join resign_higherstudies_reason hs on (hs.emp_code = e.emp_code and    e.status = hs.status)  left outer join resign_personal_reason pr on (pr.emp_code = e.emp_code and  e.status = pr.status) left outer join resign_otheremploy_reason oe on (oe.emp_code = e.emp_code and e.status = oe.status)  left outer join resign_marriage_reason mr on (mr.emp_code = e.emp_code and e.status = mr.status)left outer join resign_other_reason rr on (rr.emp_code = e.emp_code and  e.status = rr.status)left outer join employee_master e1 on (e.approved_by = e1.emp_code)left outer join employee_master e2 on (e.cancel_by = e2.emp_code) where e.emp_code = m.emp_code   and e.emp_code = ec.emp_code   and m.emp_code = ec.emp_code   and m.branch_id = ec.branch_id   and m.branch_id = b.BRANCH_ID   and e.status in (0, 1, 2, 3, 5)    and ep.perm_pin=ps.sr_number   and ps.district_id=ds.district_id   and ds.state_id=st.state_id   and ep.emp_code=e.emp_code and m.emp_code=f.emp_code and f.firm_id=" & fir & " and to_date(e.resign_dt) between to_date(" & fdt & ") and to_date(" & tdt & ")").Tables(0)
        ElseIf (dt2.Rows(0)(0) = usr) Then
            dt = oh.ExecuteDataSet("select e.emp_code,m.emp_name,b.BRANCH_NAME,ec.gender,b.area_name,b.reg_name,b.ZONAL_NAME,st.state_name,ec.designation, ec.exp_day, ec.qualification,to_date(e.enter_dt) as Apply_dt, to_date(e.resign_dt) as Resign_dt, to_date(e.relieve_dt) as Relieve_dt, case  when e.reason = 1 then  hs.college_nm || ' , ' || hs.course || ' , ' || hs.durtion  else   case        when e.reason = 2 then          pr.reason         else          case         when e.reason = 3 then          oe.firm || ' , ' || oe.reason || ' , ' || oe.nature_work || ' , ' ||          oe.salary         else          case         when e.reason = 4 then          mr.partner_name || ' , ' || mr.job_partner || ' , ' ||    mr.place_marriage  else   case  when e.reason = 5 then  rr.reason       end end end end end as reason,       case         when e.status = 0 then          'Applied' else case  when e.status = 1 then 'Approved' else  case  when e.status = 2 then 'Resigned' else  case when e.status = 3 then  'Cancelled'  else   case  when e.status = 5 then 'Processed'  end end end end end as status,e.approved_by || '--' || e1.emp_name as approved_by,to_date(e.approve_dt) as approve_dt,e.cancel_by || '--' || e2.emp_name as cancel_by,to_date(e.cancel_dt) as Cancel_dt  from employee_master  m, employ_firm f ,employee_current ec,       branch_dtl_new   b,        post_master      ps,       district_master  ds,       state_master     st,       employ_personal_dtl ep,       m_resign_appl    e  left outer join resign_higherstudies_reason hs on (hs.emp_code = e.emp_code and    e.status = hs.status)  left outer join resign_personal_reason pr on (pr.emp_code = e.emp_code and  e.status = pr.status) left outer join resign_otheremploy_reason oe on (oe.emp_code = e.emp_code and e.status = oe.status)  left outer join resign_marriage_reason mr on (mr.emp_code = e.emp_code and e.status = mr.status)left outer join resign_other_reason rr on (rr.emp_code = e.emp_code and  e.status = rr.status)left outer join employee_master e1 on (e.approved_by = e1.emp_code)left outer join employee_master e2 on (e.cancel_by = e2.emp_code) where e.emp_code = m.emp_code   and e.emp_code = ec.emp_code   and m.emp_code = ec.emp_code   and m.branch_id = ec.branch_id   and m.branch_id = b.BRANCH_ID   and e.status in (0, 1, 2, 3, 5)    and ep.perm_pin=ps.sr_number   and ps.district_id=ds.district_id   and ds.state_id=st.state_id   and ep.emp_code=e.emp_code and m.emp_code=f.emp_code and f.firm_id=" & fir & "  and  to_date(e.resign_dt) between to_date(" & fdt & ") and to_date(" & tdt & ")").Tables(0)
        Else
            dt = oh.ExecuteDataSet("select distinct e.emp_code,m.emp_name,b.BRANCH_NAME,ec.gender,b.area_name,b.reg_name,b.ZONAL_NAME,st.state_name,ec.designation,ec.exp_day, to_date(e.enter_dt) as Apply_dt,  to_date(e.resign_dt) as Resign_dt,to_date(e.relieve_dt) as Relieve_dt,  case  when e.reason = 1 then  hs.college_nm || ' , ' || hs.course || ' , ' || hs.durtion else  case  when e.reason = 2 then  pr.reason   else   case   when e.reason = 3 then  oe.firm || ' , ' || oe.reason || ' , ' || oe.nature_work || ' , ' || oe.salary   else  case   when e.reason = 4 then   mr.partner_name || ' , ' || mr.job_partner || ' , ' ||  mr.place_marriage else    case  when e.reason = 5 then   rr.reason   end end end end end as reason,  case   when e.status = 0 then 'Applied'  else   case    when e.status = 1 then 'Approved' else   case   when e.status = 2 then 'Resigned'  else   case    when e.status = 3 then    'Cancelled' end end end end as status, e.approved_by || '--' || e1.emp_name as approved_by, to_date(e.approve_dt) as approve_dt, e.cancel_by || '--' || e2.emp_name as cancel_by,                to_date(e.cancel_dt) as Cancel_dt  from employee_master     m,       employee_current    ec,       branch_dtl_new      b,       post_master         ps,       district_master     ds,       state_master        st,       employ_personal_dtl ep,       m_resign_appl       e  left outer join resign_higherstudies_reason hs on (hs.emp_code =  e.emp_code and  e.status = hs.status)  left outer join resign_personal_reason pr on (pr.emp_code = e.emp_code and   e.status = pr.status)  left outer join resign_otheremploy_reason oe on (oe.emp_code = e.emp_code and  e.status = oe.status)  left outer join resign_marriage_reason mr on (mr.emp_code = e.emp_code and  e.status = mr.status) left outer join resign_other_reason rr on (rr.emp_code = e.emp_code and  e.status = rr.status)left outer join employee_master e1 on (e.approved_by = e1.emp_code)  left outer join employee_master e2 on (e.cancel_by = e2.emp_code) where e.emp_code = m.emp_code   and e.emp_code = ec.emp_code  and m.emp_code = ec.emp_code   and m.branch_id = ec.branch_id   and m.branch_id = b.BRANCH_ID   and e.status in (0, 1, 2, 3)   and ep.perm_pin = ps.sr_number   and ps.district_id = ds.district_id   and ds.state_id = st.state_id   and ep.emp_code = e.emp_code   and e.emp_code =  '" & usr & "'   and to_date(e.resign_dt) between to_date(" & fdt & ") and       to_date(" & tdt & ")").Tables(0)
        End If

        report.Load(Server.MapPath("new_resign_report.rpt"), OpenReportMethod.OpenReportByTempCopy)
        report.Database.Tables("neresign").SetDataSource(dt)
        report.SetParameterValue("FIRM", Session("firm_name"))
        Me.CrystalReportViewer1.ReportSource = report
    End Sub
    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload
        report.Dispose()
        report.Close()
        GC.Collect()
    End Sub
End Class
