Partial Class uc_date
    Inherits System.Web.UI.UserControl
    Public f_name As String
    Public out_date As String
    Dim start_dt As String
    Dim start_dt1 As String
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        f_name = Me.ClientID
        Me.Text1.ID = "txt_date_html"
        If start_dt = "" Then
            Me.Text1.Value = Format(Date.Now, "dd/MMM/yyyy")
        Else
            Me.Text1.Value = start_dt
        End If

        Dim c As String = f_name + "val_date()"
        Me.Text1.Attributes.Add("onblur", c)
        Dim java_script As New System.Text.StringBuilder
        java_script.Append("var us_name_date,sys_date;us_name_date='" + f_name + "_txt_date_html';sys_date='" & Format(Date.Now, "dd/MMM/yyyy") & "';")
        ' java_script.Append("var " + f_name + "us_name_date," + f_name + "sys_date,cont_name;" + f_name + "us_name_date='" + f_name + "_txt_date_html';" + f_name + "sys_date='" & Format(Date.Now, "dd/MMM/yyyy") & "';cont_name='" + f_name + "';")
        java_script.Append("function " + f_name + "val_date()")
        java_script.Append("{")
        java_script.Append("    " + f_name + "Date_finder(document.getElementById('" + f_name + "_txt_date_html').value,'" + f_name + "_txt_date_html',1);")
        java_script.Append("}")

        java_script.Append("function " + f_name + "y2k(number) { return (number < 1000) ? number + 1900 : number; }")

        java_script.Append("function " + f_name + "isDate(day,month,year) ")
        java_script.Append("{")
        java_script.Append("    var today = new Date();")
        java_script.Append("    year = ((!year) ? " + f_name + "y2k(today.getYear()):year);")
        java_script.Append("    month = ((!month) ? today.getMonth():month-1);")
        java_script.Append("    if (!day) return false;")
        java_script.Append("        var test = new Date(year,month,day);")
        java_script.Append("    if ( (" + f_name + "y2k(test.getYear()) == year) && (month == test.getMonth()) && (day == test.getDate()) )")
        java_script.Append("        return true;")
        java_script.Append("    else")
        java_script.Append("        return false;")
        java_script.Append("}")

        java_script.Append("function " + f_name + "Date_finder(date_str,ctl_id,disp)")
        java_script.Append("{")
        java_script.Append("    var date_out;")
        java_script.Append("    var mon= new Array('','JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC');")
        java_script.Append("    if (date_str=='' )")
        java_script.Append("    { ")
        java_script.Append("        alert('Enter the Date');")
        java_script.Append("    }")
        java_script.Append("    else  ")
        java_script.Append("    { ")
        java_script.Append("        if(date_str.indexOf('-')>0 || date_str.indexOf('/')>0 || date_str.indexOf(' ')>0)")
        java_script.Append("        {")
        java_script.Append("            if(date_str.indexOf('-')>0)")
        java_script.Append("            {")
        java_script.Append("                date_out=" + f_name + "format_date(date_str,'-');")
        java_script.Append("                if(disp==1)")
        java_script.Append("                {")
        java_script.Append("                    if(date_out==0)")
        java_script.Append("                    {")
        java_script.Append("                        document.getElementById(ctl_id).value=date_str; ")
        java_script.Append("                    }")
        java_script.Append("                    else")
        java_script.Append("                    {")
        java_script.Append("                        var str_dt=date_out.split('/');")
        java_script.Append("                        if(" + f_name + "isDate(parseInt(str_dt[0],10),parseInt(str_dt[1],10),parseInt(str_dt[2],10)))")
        java_script.Append("                        {")
        java_script.Append("                            document.getElementById(ctl_id).value=str_dt[0]+'/'+mon[parseInt(str_dt[1])]+'/'+str_dt[2];")
        java_script.Append("                            document.getElementById('" + out_date + "').value=str_dt[0]+'/'+mon[parseInt(str_dt[1],10)]+'/'+str_dt[2]; ")
        ' java_script.Append("                            alert(document.getElementById('" + out_date + "').value)")
        java_script.Append("                        }")
        java_script.Append("                        else")
        java_script.Append("                        {")
        java_script.Append("                            alert('The Date is Not Valid');")
        java_script.Append("                        }")
        java_script.Append("                    }")
        java_script.Append("                }")
        java_script.Append("            else")
        java_script.Append("            {")
        java_script.Append("                alert(date_out);")
        java_script.Append("            }")
        java_script.Append("        }")
        java_script.Append("        else if(date_str.indexOf('/')>0) ")
        java_script.Append("        {")
        java_script.Append("            date_out=" + f_name + "format_date(date_str,'/'); ")
        java_script.Append("            if(disp==1)")
        java_script.Append("            {")
        java_script.Append("                if(date_out==0)")
        java_script.Append("                {")
        java_script.Append("                    document.getElementById(ctl_id).value=date_str; ")
        java_script.Append("                }")
        java_script.Append("                else")
        java_script.Append("                {")
        java_script.Append("                    var str_dt=date_out.split('/');")
        java_script.Append("                    if(" + f_name + "isDate(parseInt(str_dt[0],10),parseInt(str_dt[1],10),parseInt(str_dt[2],10)))")
        java_script.Append("                    {")
        java_script.Append("                        document.getElementById(ctl_id).value=str_dt[0]+'/'+mon[parseInt(str_dt[1])]+'/'+str_dt[2];")
        java_script.Append("                        document.getElementById('" + out_date + "').value=str_dt[0]+'/'+mon[parseInt(str_dt[1],10)]+'/'+str_dt[2]; ")
        '  java_script.Append("                        alert(document.getElementById('" + out_date + "').value)")
        java_script.Append("                    }")
        java_script.Append("                    else")
        java_script.Append("                    {")
        java_script.Append("                        alert('The Date is Not Valid');")
        java_script.Append("                    }")
        java_script.Append("                }")
        java_script.Append("            }")
        java_script.Append("            else")
        java_script.Append("            {")
        java_script.Append("                alert(date_out);")
        java_script.Append("            }")
        java_script.Append("        }")
        java_script.Append("        else if (date_str.indexOf(' ')>0)")
        java_script.Append("        {")
        java_script.Append("            date_out=" + f_name + "format_date(date_str,' '); ")
        java_script.Append("            if(disp==1)")
        java_script.Append("            {")
        java_script.Append("                if(date_out==0)")
        java_script.Append("                {")
        java_script.Append("                    document.getElementById(ctl_id).value=date_str; ")
        java_script.Append("                }")
        java_script.Append("                else")
        java_script.Append("                {")
        java_script.Append("                    var str_dt=date_out.split('/');")
        java_script.Append("                    if(" + f_name + "isDate(parseInt(str_dt[0],10),parseInt(str_dt[1],10),parseInt(str_dt[2],10)))")
        java_script.Append("                    {")
        java_script.Append("                        document.getElementById(ctl_id).value=str_dt[0]+'/'+mon[parseInt(str_dt[1],10)]+'/'+str_dt[2]; ")
        java_script.Append("                        document.getElementById('" + out_date + "').value=str_dt[0]+'/'+mon[parseInt(str_dt[1],10)]+'/'+str_dt[2]; ")
        ' java_script.Append("                        alert(document.getElementById('" + out_date + "').value)")
        java_script.Append("                    }")
        java_script.Append("                    else")
        java_script.Append("                    {")
        java_script.Append("                        alert('The Date is Not Valid');")
        java_script.Append("                    }")
        java_script.Append("                }")
        java_script.Append("            }")
        java_script.Append("            else")
        java_script.Append("            {")
        java_script.Append("                alert(date_out);")
        java_script.Append("            }")
        java_script.Append("        }")
        java_script.Append("        else")
        java_script.Append("        {")
        java_script.Append("            alert('Date is to be validated');")
        java_script.Append("        }")
        java_script.Append("    }")
        java_script.Append(" }")
        java_script.Append("}")

        java_script.Append("function " + f_name + "format_date(date_in,anil)")
        java_script.Append("{")
        java_script.Append("    var day,month,year,temp,flag=0,ex_falg=0;")
        java_script.Append("    day=date_in.substring(0,date_in.indexOf(anil));")
        java_script.Append("    if(!isNaN(day))")
        java_script.Append("    {")
        java_script.Append("        if(day>=1 && day<=32)")
        java_script.Append("        {")
        java_script.Append("            day=day;")
        java_script.Append("        }")
        java_script.Append("        else")
        java_script.Append("        {")
        java_script.Append("            day=0;")
        java_script.Append("            flag=1;")
        java_script.Append("        }")
        java_script.Append("    }")
        java_script.Append("    else")
        java_script.Append("    {")
        java_script.Append("        flag=4;")
        java_script.Append("    }")
        java_script.Append("    temp=date_in.substring(date_in.indexOf(anil)+1);")
        'java_script.Append("    alert(temp);")
        'java_script.Append("    alert(temp.substring(0,temp.indexOf(anil)));")
        java_script.Append("    month=parseInt(temp.substring(0,temp.indexOf(anil)),10);")
        'java_script.Append("    alert(month);")
        java_script.Append("    if(!(isNaN(month)))")
        java_script.Append("    {")
        java_script.Append("        if(month>=1 && month<=12 )")
        java_script.Append("        {")
        java_script.Append("            month=month;")
        java_script.Append("        }")
        java_script.Append("        else")
        java_script.Append("        {")
        java_script.Append("            month=0;")
        java_script.Append("            flag=2;")
        java_script.Append("        }")
        java_script.Append("    }")
        java_script.Append("    else")
        java_script.Append("    {")
        java_script.Append("        month=temp.substring(0,temp.indexOf(anil)).toUpperCase();")
        java_script.Append("        if(month=='JAN')")
        java_script.Append("        {")
        java_script.Append("            month=1;")
        java_script.Append("        }")
        java_script.Append("        else if(month=='FEB')")
        java_script.Append("        {")
        java_script.Append("            month=2;")
        java_script.Append("        }")
        java_script.Append("        else if( month=='MAR')")
        java_script.Append("        {")
        java_script.Append("            month=3;")
        java_script.Append("        }")
        java_script.Append("        else if(month=='APR')")
        java_script.Append("        {")
        java_script.Append("            month=4;")
        java_script.Append("        }")
        java_script.Append("        else if(month=='MAY')")
        java_script.Append("        {")
        java_script.Append("            month=5;")
        java_script.Append("        }")
        java_script.Append("        else if(month=='JUN')")
        java_script.Append("        {")
        java_script.Append("            month=6;")
        java_script.Append("        }")
        java_script.Append("        else if(month=='JUL')")
        java_script.Append("        {")
        java_script.Append("            month=7;")
        java_script.Append("        }")
        java_script.Append("        else if(month=='AUG')")
        java_script.Append("        {")
        java_script.Append("            month=8;")
        java_script.Append("        }")
        java_script.Append("        else if(month=='SEP')")
        java_script.Append("        {")
        java_script.Append("            month=9;")
        java_script.Append("        }")
        java_script.Append("        else if(month=='OCT')")
        java_script.Append("        {")
        java_script.Append("            month=10;")
        java_script.Append("        }")
        java_script.Append("        else if(month=='NOV')")
        java_script.Append("        {")
        java_script.Append("            month=11;")
        java_script.Append("        }")
        java_script.Append("        else if(month=='DEC')")
        java_script.Append("        {")
        java_script.Append("            month=12;")
        java_script.Append("        }")
        java_script.Append("        else")
        java_script.Append("        {")
        java_script.Append("            flag=5;")
        java_script.Append("        }")
        java_script.Append("    }")
        java_script.Append("    temp=temp.substring(temp.indexOf(anil)+1);")
        java_script.Append("    if(temp.length<5)")
        java_script.Append("    {")
        java_script.Append("        year=temp;")
        java_script.Append("        if(!(isNaN(year)))")
        java_script.Append("        {  ")
        java_script.Append("            if(year.length==4)")
        java_script.Append("            {")
        java_script.Append("                year=year;")
        java_script.Append("            }")
        java_script.Append("            else")
        java_script.Append("            {")
        java_script.Append("                year=0;")
        java_script.Append("                flag=3;")
        java_script.Append("            }")
        java_script.Append("        } ")
        java_script.Append("        else")
        java_script.Append("        {")
        java_script.Append("            flag=6;")
        java_script.Append("        }")
        java_script.Append("    }")
        java_script.Append("    else")
        java_script.Append("    {")
        java_script.Append("        flag=3;")
        java_script.Append("    }")
        java_script.Append("    if(flag==0)")
        java_script.Append("    {")
        'java_script.Append("       //alert(day +'/'+month +'/'+year);")
        java_script.Append("        return(day +'/'+month +'/'+year);")
        java_script.Append("    }")
        java_script.Append("    else ")
        java_script.Append("    {   ")
        java_script.Append("        if(flag==1 || flag==4)")
        java_script.Append("        {")
        java_script.Append("            alert('Invalied Day ');")
        java_script.Append("        }")
        java_script.Append("        else if(flag==2 || flag==5)")
        java_script.Append("        {")
        java_script.Append("            alert('Invalied Month Enter  a Number between 1(JAN) to 12(DEC) or JAN to DEC ');")
        java_script.Append("        }")
        java_script.Append("        else if(flag==3 || flag==6)")
        java_script.Append("        {")
        java_script.Append("            if(flag==3)")
        java_script.Append("            {")
        java_script.Append("            alert('The format is CCYY or eg:2006');")
        java_script.Append("            }")
        java_script.Append("            else")
        java_script.Append("            {")
        java_script.Append("                alert('Invalied Year');")
        java_script.Append("            }")
        java_script.Append("        }")
        java_script.Append("        else")
        java_script.Append("        {")
        java_script.Append("            alert('Date Is not In Correct Format');  ")
        java_script.Append("        }")
        java_script.Append("    return(0);")
        java_script.Append("    }    ")
        java_script.Append("}")
        Page.ClientScript.RegisterClientScriptBlock(Me.GetType, "JavaScript" + f_name, java_script.ToString(), True)
    End Sub
    WriteOnly Property fun_name() As String
        Set(ByVal value As String)
            f_name = value
        End Set
    End Property
    WriteOnly Property blu_date() As String
        Set(ByVal value As String)
            out_date = value
        End Set
    End Property
    Public Property fromdate()
        Get
            fromdate = Me.Text1.Value
        End Get
        Set(ByVal Value)

        End Set
    End Property
    Public Property start_date() As String
        Get
            Return (start_dt)
        End Get
        Set(ByVal value As String)
            start_dt = value
        End Set
    End Property
End Class
